### ISSUE TITLE
Symfony .env & .env.local

### ISSUE THREAD

**Issue by MatthD** [codeshifu/sync-dotenv#13]
Hi , 

In symfony 4.3 they changed the way to use .env files , now .env file are the example & are commited into repo & we have to overwrite them with .env.local.

So to use `sync-dotenv` we should be able to indicate source / destination .

I will do a PR if got some time

**Comment by codeshifu** [comment]
Hey @MatthD, thanks for submitting the issue. I believe I have already worked on [this](https://github.com/codeshifu/sync-dotenv/pull/12) and should roll out tomorrow
