### ISSUE TITLE
[Suggestion]: Support for syncing multiple `.env.*` files

### ISSUE THREAD

**Issue by tdeekens** [codeshifu/sync-dotenv#14]
Thanks for this great library. It solves an issue we've had with keeping `.env` files in sync and we're super glad we've found it.

We are wondering if it would be of interest for the library to support "fan-out" to multiple `.env` files from one `.env.template`.

Our setup often looks like:

```
.env.template
.env.local
.env.staging
.env.production
```

this helps us simulating and configuring interaction with different parts of the system. We would love to sync from the `.env.template` to all other env files. This would require, to my understanding, some globbing (in the root) by the library instead of relying on one file. 

Thanks.

**Comment by codeshifu** [comment]
Thanks, @tdeekens for submitting this issue. Although this is a really nice suggestion, it's not a priority right now but you can rest assured I'll look into it.

**Comment by codeshifu** [comment]
Hi @tdeekens, I'm happy to announce that your request has been fulfilled. All thanks go to @akhilome for this [addition](https://github.com/codeshifu/sync-dotenv/pull/15)

Support for syncing with multiple `.env.*` is now available in [v2.2.0](https://www.npmjs.com/package/sync-dotenv/v/2.2.0) 🎉
