### ISSUE TITLE
Synchronize Comments

### ISSUE THREAD

**Issue by johannesschobel** [codeshifu/sync-dotenv#18]
Dear @codeshifu ,

thanks for this wonderful package - i really like it.
I recently stumbled upon the issue, that i have comments in my `.env` file. I would like to synchronize these comments with my `.env.example` file.

Would you consider adding this feature to your library?
Thanks a lot!

**Comment by codeshifu** [comment]
@johannesschobel thanks for the feedback. It'll be added pretty soon :)

**Comment by johannesschobel** [comment]
wow, thanks a lot for this fast answer.. 
looking forward to it!

**Comment by codeshifu** [comment]
Hi @johannesschobel, sorry I been busy. This request has been added and now available in [v2.3.0](https://github.com/codeshifu/sync-dotenv/releases/tag/v2.3.0)! Thanks again

**Comment by johannesschobel** [comment]
Awesome.. will update next week :)

**Comment by johannesschobel** [comment]
Dear @codeshifu , thanks a lot for your update! I already updated it.
When adding comments to my `.env` file, however, i stumbled upon the issue, that i would also like to have comments IN LINE to indicate the way, this property needs to be set

Consider the following example:
```
# api environment
APP_URI=http://localhost:3000 # without trailing slash
API_PREFIX=api # without trailing slash
LOG_LEVEL=debug # error, debug, info
...
```

When i then synchronize the `.env` file to a `.env.example` file, it looks like this:
```
# api environment
APP_URI=
API_PREFIX=
LOG_LEVEL=
...
```

Basically, the comments that were put next to the value are lost. So if one would like to fill in the `.env` file himself, he does not know, what log levels are available (error, debug, info) or whatever.. Do you know, what i mean?

Would it be possible to keep the comments that are placed inline as well?
All the best!

**Comment by codeshifu** [comment]
Ha! I anticipated that but didn't really think people do that a lot. I'll see to it. Thanks @johannesschobel

**Comment by johannesschobel** [comment]
damn.. i should have made my point clearer in the first issue :D haha.. thanks a lot!

**Comment by codeshifu** [comment]
Haha. No worries mate

**Comment by codeshifu** [comment]
@johannesschobel added support for inline comments [here](https://github.com/codeshifu/sync-dotenv/pull/20). Please update to **v2.4.0**

**Comment by johannesschobel** [comment]
thanks a lot, man.. ^^ will update asap and give feedback!
