### ISSUE TITLE
Reverse sync?

### ISSUE THREAD

**Issue by briancoit** [codeshifu/sync-dotenv#23]
I have a use-case to sync .env and .env.example (or .env.dist in my case) in the opposite direction - pushing updates on the .env file whenever .env.dist additions are made. Not the immediate use-case you cover, but it feels possible and equivalent.

Currently this fails, due to some check on the .env file name. Is this check necessary? 

```
> sync-dotenv --env .env.dist --sample .env

Cannot sync .env with .env
```

**Comment by f-liva** [comment]
How to do this?
