### ISSUE TITLE
Strange behaviour with KEY=#value 

### ISSUE THREAD

**Issue by leandrojdl** [codeshifu/sync-dotenv#25]
I have to store an env variable with a slack channel starting with `#` character.

**Scenario 1**:

`.env`:
```
# Default channel
CHANNEL=#general
```
`.env.example`:
```
# Default channel
CHANNEL=#random
```

run `sync-dotenv` then

`.env.example`:
```
CHANNEL= #general
```

Comment was deleted and value was overwritten with `.env` value and a spaces was added.

**Scenario 2**:

If I use quotes (singles or doubles)

`.env`:
```
# Default channel
CHANNEL='#general'
```
`.env.example`:
```
# Default channel
CHANNEL='#random'
```

run `sync-dotenv` then

`.env.example`:
```
CHANNEL= 
```

It deletes both, comment and value from key.

So I can't keep my `.env.example` with a useful example.

It would be great if you could consider this case.

Thanks

**Comment by codeshifu** [comment]
@leandrojdl thanks for reporting this issue. I'll look into it

**Comment by codeshifu** [comment]
@leandrojdl There was a problem with the release build of the library in [v2.5.0](https://www.npmjs.com/package/sync-dotenv/v/2.5.0) using [microbundle][https://www.npmjs.com/package/microbundle) as reported here #28. 

This has been fixed. Please consider migrating to [v2.6+](https://www.npmjs.com/package/sync-dotenv/v/2.6.0)
