### ISSUE TITLE
Line endings converted from LF to CRLF

### ISSUE THREAD

**Issue by cmckni3** [codeshifu/sync-dotenv#33]
I am using macOS with a `.env` file with LF (\n) line endings. Running `sync-dotenv` produced a `.env.example` file with CRLF line endings (\r\n).

**Comment by codeshifu** [comment]
Hi @cmckni3, thanks for filing this issue. I'll look into it if I have some free time this week or latest by weekend. You are welcome to submit a PR if this is urgent for you :)
