### ISSUE TITLE
Cannot use 'example.env' as example file name

### ISSUE THREAD

**Issue by udidoron** [codeshifu/sync-dotenv#9]
Not a big deal, of course, but it's a tiny issue nonetheless - 

Currently, *any* sample filename provided via the CLI that ends with `.env` [throws an error](https://github.com/codeshifu/sync-dotenv/blob/1ea41f2b72b08c2bf74df0a537bd1c3ff69461e0/lib/lib.ts#L80).  
While I understand the reasoning - can't sync `.env` itself with `.env` - my team uses `example.env` as the filename for the example file (as if to say, "here's an example .env file").   
Would it be OK to change the check for exclusively `.env` files - not all files that end with `.env`, or is this a matter of policy (or a best practice I'm unaware of)?  

Thanks for your help!

**Comment by codeshifu** [comment]
That's actually true @udidoron. Although the check was put in place to ensure the users don't try to sync with the same file, not all (target) files that end with `.env ` is the same as the source as you have rightly pointed out.

This will be worked on. Thank you.

**Comment by udidoron** [comment]
Thank you very much for the quick and helpful response, @codeshifu!

**Comment by codeshifu** [comment]
@udidoron thank you for submitting the issue, it's going to be helpful to others. 🥇

**Comment by codeshifu** [comment]
[v2.0.3](https://www.npmjs.com/package/sync-dotenv/v/2.0.3) is now available as a fix for this issue 🎉
